// Generated by CoffeeScript 1.8.0
(function() {
  var _compare, _initHook;

  exports.addAction = function(method, action, index) {
    var actions;
    _initHook(method);
    actions = method.__myHook__.actions;
    actions.push({
      action: action,
      index: index || 0
    });
    return actions.sort(_compare);
  };

  exports.doAction = function() {
    var action, actions, method, myArguments, _i, _len, _results;
    method = arguments.callee.caller;
    if (!method.hasOwnProperty('__myHook__')) {
      return;
    }
    myArguments = method["arguments"];
    actions = method['__myHook__'].actions;
    _results = [];
    for (_i = 0, _len = actions.length; _i < _len; _i++) {
      action = actions[_i];
      _results.push(action.action.apply(method, myArguments));
    }
    return _results;
  };

  exports.removeAction = function(method, actionToRemove) {
    var actions;
    if (!method.hasOwnProperty('__myHook__' || method['__myHook__'].actions.length === 0)) {
      return;
    }
    actions = method['__myHook__'].actions;
    return method['__myHook__'].actions = actions.filter(function(action) {
      return action.action !== actionToRemove;
    });
  };

  _compare = function(value1, value2) {
    return value2.index - value1.index;
  };

  _initHook = function(method) {
    if (!method.hasOwnProperty('__myHook__')) {
      return method.__myHook__ = {
        actions: []
      };
    }
  };

}).call(this);

//# sourceMappingURL=hook.js.map
